#!/usr/bin/python 
"""
Given a list of directories, prints out a JavaScript array of paths to files 
that end in "_test.html". The output will look something like: 
var _allTests = [ 
	"example/emailvalidator_test.html", 
	"example/factorial_test.html"]; 
""" 
import os.path 
import sys
import json

def add_data_files(test_files, dirname, names):
  """File names that end in "_test.html" are added to test_files.""" 
  for name in names: 
    path = os.path.join(dirname, name) 
    if os.path.isfile(path) and (name.endswith('.sbgn') or name.endswith('.json') or name.endswith('.jsbgn') or name.endswith('.xml')):
      pathArg = path.replace('\\', '/').replace('./','')
      test_files.append(pathArg)
      
def find_data_files(directory):
  """Returns the list of files in directory that end in "_test.html".""" 
  if not os.path.exists(directory) or not os.path.isdir(directory): 
    raise Exception('Not a directory: ' + directory) 
  data_files = []
  os.path.walk(directory, add_data_files, data_files)
  return data_files
  
def usage(): 
  """Displays a message to the user when invalid input is supplied.""" 
  print 'Specify a list of directories that contain _test.html files' 
  
def main(): 
  """Prints the list of JS test files to standard out.""" 
  if len(sys.argv) < 2: 
    usage() 
    sys.exit(-1) 
  else: 
    data_files = []
    data_objects={}
    for directory in sys.argv[1:]: 
      data_files.extend(find_data_files(directory))
    for file_name in data_files:
      data_objects[file_name]={'fileName':file_name,'content':open(file_name).read()}
    print '//This file is automatically generated by ant build-test-data. Please do not edit it manually.\n var _allData = ',
    print json.dumps(data_objects) + ';'
if __name__ == '__main__': 
  main() 